---
# tasks file for mediapeers.filebeat

- name: Add elastic apt repo key (for all elastic software)
  apt_key:
    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present

# Install filebeat as a logstash client (to deliver logs), just for demoing

- name: Add filebeat (Elastic) apt repo
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ filebeat_major_version }}/apt stable main"
    update_cache: yes
    state: present

- name: Install filebeat apt package
  apt:
    name: filebeat
    state: present
  notify:
    - clean registry
    - restart filebeat

- name: Configure filebeat to read from logfiles and deliver to logstash (add config file)
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify:
    - restart filebeat

- name: Run all notified handlers before moving on
  meta: flush_handlers

- name: Enable filebeat on bootup and ensure it's started
  service:
    name: filebeat
    enabled: yes
    state: started
