---
# handlers file for mediapeers.filebeat

- name: restart filebeat
  service:
    name: filebeat
    state: restarted

- name: clean registry
  file:
    path: /var/lib/filebeat/registry/filebeat/
    state: absent
